# Restart webpack-dev-server if you make changes here
default: &default
  enabled: true
  host: 0.0.0.0
  port: 3001

development:
  <<: *default

test:
  <<: *default
  enabled: false

production:
  <<: *default
  enabled: false
